server:
  port: 8080

spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:testcontainers}?currentSchema=${DATABASE_SCHEMA:testcontainers}"
    username: ${DATABASE_USERNAME:testcontainers_user}
    password: ${DATABASE_PASSWORD:testcontainers_user}
  liquibase:
    change-log: "classpath:db-migrations/changelog.xml"